[build]
  command = "export CI=false && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.x"
  DISABLE_ESLINT_PLUGIN = "true"
  CI = "false"

[dev]
  framework = "create-react-app"
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: data: blob: 'unsafe-inline' 'unsafe-eval';"
